destination: ./doc
source: ./src
baseurl: /doc
markdown: kramdown

kramdown:
  toc_levels: 2..3

track_api_host: track.admasterapi.com
track_site_host: www.trackmaster.com.cn

open_site_host: open.admaster.com.cn
weibo_api_host: weibo.admasterapi.com
survey_api_host: survey.admasterapi.com
